apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecoledger-ingress
  # Remove rewrite annotation or update it as per above
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ecoledger-backend-service
            port:
              number: 5090
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ecoledger-frontend-service
            port:
              number: 80

