apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoledger-backend
  labels:
    app: ecoledger-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecoledger-backend
  template:
    metadata:
      labels:
        app: ecoledger-backend
    spec:
      containers:
      - name: backend
        image: laiba777/ecoledger-backend:backend-v4
        ports:
        - containerPort: 5090
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
